<#
This script downloads icons from Dungeons of Dredmor.

The files can be seen here. Only 64x64 images from this page are in the below list.
https://dungeonsofdredmor.fandom.com/wiki/Special:ListFiles?limit=9999

There are about 399 icons totalling about 1.24 MB.

Please see the readme.md here for more information:
https://github.com/d16-nichevo/vtt-icons-download-scripts/blob/main/README.md
#>

wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/80/Holding_axe_up.png -o Holding_axe_up.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e0/Encrust_weapon.png -o Encrust_weapon.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/bd/Encrust_shield.png -o Encrust_shield.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/aa/Encrust_ring.png -o Encrust_ring.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/d4/Encrust_pants.png -o Encrust_pants.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/50/Encrust_helm.png -o Encrust_helm.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4d/Encrust_gauntlets.png -o Encrust_gauntlets.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b0/Encrust_crossbow.png -o Encrust_crossbow.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/ee/Encrust_boots.png -o Encrust_boots.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c8/Encrust_belt.png -o Encrust_belt.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/39/Encrust_armour.png -o Encrust_armour.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/ab/Encrust_amulet.png -o Encrust_amulet.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/45/Magic_gate64.png -o Magic_gate64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e8/Siegfried.png -o Siegfried.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/f4/Impish_Diggle.png -o Impish_Diggle.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/ce/Trained_Hunting_Diggle.png -o Trained_Hunting_Diggle.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/84/Enchanted_Plaguetato.png -o Enchanted_Plaguetato.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/22/Veteran_Crustaceanoid.png -o Veteran_Crustaceanoid.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/55/Hungry_Diggle.png -o Hungry_Diggle.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/3e/Thirsty_Diggle.png -o Thirsty_Diggle.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/62/Animate_Blood.png -o Animate_Blood.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/40/Animated_Oil.png -o Animated_Oil.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/16/Summon_Slime.png -o Summon_Slime.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4c/Deep_Fungus_Diggle.png -o Deep_Fungus_Diggle.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/01/Core_diggle64.png -o Core_diggle64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/01/SamuraiBot_Mk3.png -o SamuraiBot_Mk3.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/92/Diggle_devil64.png -o Diggle_devil64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/bf/Digglegod_fertility64.png -o Digglegod_fertility64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/aa/Vlad_Digula.png -o Vlad_Digula.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b0/Existential_Raven.png -o Existential_Raven.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6a/Ancient_Rutabaga.png -o Ancient_Rutabaga.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/98/Phlegmatic_Animation.png -o Phlegmatic_Animation.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/cb/Fruit_Treant.png -o Fruit_Treant.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/06/Fish_Paladin.png -o Fish_Paladin.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/cd/Digglegod_secrets.png -o Digglegod_secrets.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b6/Devil_buff_icon.jpg -o Devil_buff_icon.jpg
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/ab/Sonic_cannon64.png -o Sonic_cannon64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/7e/Rebreather_mask64.png -o Rebreather_mask64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/0f/Gas_canister64.png -o Gas_canister64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/92/Clockwork_reflexes64.png -o Clockwork_reflexes64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/73/Chemic_pilferer64.png -o Chemic_pilferer64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/78/Baromatic_vortex64.png -o Baromatic_vortex64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/ed/Aetheric_death_ray64.png -o Aetheric_death_ray64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/bc/Acidical_projector64.png -o Acidical_projector64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/83/Warlocks_challenge64.png -o Warlocks_challenge64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/f7/Supercharged64.png -o Supercharged64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/7a/Puissant_touch64.png -o Puissant_touch64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6c/Puissant_field64.png -o Puissant_field64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/13/Manacalypse64.png -o Manacalypse64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4c/Chronomantic_twist64.png -o Chronomantic_twist64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/51/Battle_form64.png -o Battle_form64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/cf/Arcane_capacitor64.png -o Arcane_capacitor64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b4/Steam_charge64.png -o Steam_charge64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/d8/Tech_scavenger64.png -o Tech_scavenger64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/9c/Rocket_jump64.png -o Rocket_jump64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4d/Rocket_fist64.png -o Rocket_fist64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/3e/Mecha_stomp64.png -o Mecha_stomp64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/89/Damper64.png -o Damper64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/99/Augmented_limbs64.png -o Augmented_limbs64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/a4/Xenochemistry64.png -o Xenochemistry64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b8/Skepticism64.png -o Skepticism64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/13/Rational_explanation64.png -o Rational_explanation64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/3f/Close_encounter64.png -o Close_encounter64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/d8/Alien_weapon64.png -o Alien_weapon64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/36/Alien_autopsy64.png -o Alien_autopsy64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/5a/Writ_of_counterspelling64.png -o Writ_of_counterspelling64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/90/Polymorphic_injunction64.png -o Polymorphic_injunction64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/de/Objection64.png -o Objection64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4f/Gag_order64.png -o Gag_order64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/89/Confiscate_evidence64.png -o Confiscate_evidence64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/ea/Stone_toughness64.png -o Stone_toughness64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/89/Stone_fist64.png -o Stone_fist64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/88/Seismic_uppercut64.png -o Seismic_uppercut64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e2/Rock_armour64.png -o Rock_armour64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/07/Quake64.png -o Quake64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/9d/Petrification64.png -o Petrification64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/51/Sandstorm64.png -o Sandstorm64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b5/Nile64.png -o Nile64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/cd/Imhotep64.png -o Imhotep64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b9/Eye_of_ra64.png -o Eye_of_ra64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/44/Asp64.png -o Asp64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/3d/Anubis64.png -o Anubis64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b0/Vital_siphon64.png -o Vital_siphon64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c3/Haematic_phylactery64.png -o Haematic_phylactery64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/63/Invisible_geometries64.png -o Invisible_geometries64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/32/Magic_tap64.png -o Magic_tap64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/d9/Power_of_the_rod64.png -o Power_of_the_rod64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/f6/Aetherweaver64.png -o Aetherweaver64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/ac/Extra_planar_Concentration64.png -o Extra_planar_Concentration64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/79/License_to_Cast64.png -o License_to_Cast64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/69/Get_away64.png -o Get_away64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/5f/Sample_cuisine64.png -o Sample_cuisine64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/cc/Meet_people64.png -o Meet_people64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/0c/Foreign_currency64.png -o Foreign_currency64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6b/See_the_sights64.png -o See_the_sights64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/61/Relax_and_unwind64.png -o Relax_and_unwind64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/99/Helm_Daemonic_Diggle_Skull_Helm.png -o Helm_Daemonic_Diggle_Skull_Helm.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/8d/Digglegod_death64.png -o Digglegod_death64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/7f/Digglegod_digging64.png -o Digglegod_digging64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/92/Digglegod_war64.png -o Digglegod_war64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/a1/Bailout64.png -o Bailout64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/1b/Zorkmid64.png -o Zorkmid64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/ed/Hire_contractor64.png -o Hire_contractor64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/73/Insurance_fraud64.png -o Insurance_fraud64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/25/Toxic_assets64.png -o Toxic_assets64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/fc/High_interest_loan64.png -o High_interest_loan64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/86/The_bomb64.png -o The_bomb64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4e/Iron_curtain64.png -o Iron_curtain64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/ea/Vanguard_party64.png -o Vanguard_party64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/1d/Dialectical_materialism64.png -o Dialectical_materialism64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/d5/General_winter64.png -o General_winter64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/3c/Socialized_healthcare64.png -o Socialized_healthcare64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/ac/Guerrilla64.png -o Guerrilla64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/dd/Batty64.png -o Batty64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/de/Psychic_vampire64.png -o Psychic_vampire64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/a8/Music_of_the_gears64.png -o Music_of_the_gears64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4c/Fungus4_64.png -o Fungus4_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/8c/Fungus3_64.png -o Fungus3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4a/Fungus2_64.png -o Fungus2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b5/Fungus1_64.png -o Fungus1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/14/Attack_poison64.png -o Attack_poison64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/04/Vending_machine_looter64.png -o Vending_machine_looter64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6c/Eye_lasers64.png -o Eye_lasers64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/ff/See_invisible64.png -o See_invisible64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/0f/Transdimensional_dodge64.png -o Transdimensional_dodge64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/70/Aikido64.png -o Aikido64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/2f/Australian64.png -o Australian64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/78/Monster_toss64.png -o Monster_toss64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/29/Fight_in_the_shade64.png -o Fight_in_the_shade64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/9a/Forge_lord64.png -o Forge_lord64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6a/Killing_blow64.png -o Killing_blow64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/56/Body_paint64.png -o Body_paint64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/cb/Polearm_damage.png -o Polearm_damage.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e2/Polearm_offensive.png -o Polearm_offensive.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4a/Polearm_linear.png -o Polearm_linear.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/60/Polearm_sweep.png -o Polearm_sweep.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/a7/Skill_polearm.png -o Skill_polearm.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e6/Tourist.png -o Tourist.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/96/Paranormal_Investigator.png -o Paranormal_Investigator.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/18/Magical_Law.png -o Magical_Law.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/76/Egyptian_Magic.png -o Egyptian_Magic.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/03/Communist.png -o Communist.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/56/Bankster.png -o Bankster.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/02/N-dimensional_lathe_%28crafting%29.png -o N-dimensional_lathe_%28crafting%29.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/27/Skill_Maverick.png -o Skill_Maverick.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/0f/Battle_Geology.png -o Battle_Geology.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e1/Warlockery.png -o Warlockery.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/32/Rogue_Scientist.png -o Rogue_Scientist.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/f7/Clockwork_Knight.png -o Clockwork_Knight.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4e/Butcher64.png -o Butcher64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/de/Depressing_Elemental_Blast64.png -o Depressing_Elemental_Blast64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/87/Mark_of_the_Black_Eyeliner64.png -o Mark_of_the_Black_Eyeliner64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/a6/Sigil_of_Whatever64.png -o Sigil_of_Whatever64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/cd/Dampening_Field_of_Angst64.png -o Dampening_Field_of_Angst64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/a9/My_Chemical_Explosion64.png -o My_Chemical_Explosion64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/2e/The_Cure64.png -o The_Cure64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/03/Love_Will_Teleport_Us_Apart64.png -o Love_Will_Teleport_Us_Apart64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/2b/Broadside64.png -o Broadside64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/1e/The_Black_Spot64.png -o The_Black_Spot64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/f6/Mist_of_the_Corsair64.png -o Mist_of_the_Corsair64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/19/Swashbuckling64.png -o Swashbuckling64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/9e/Flames_of_The_Heckforge64.png -o Flames_of_The_Heckforge64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/2a/No_You_Are_The_Demon64.png -o No_You_Are_The_Demon64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/84/Infernal_Contract64.png -o Infernal_Contract64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/92/Abyssal_Fire64.png -o Abyssal_Fire64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/3e/Celestial_Circle64.png -o Celestial_Circle64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/1c/Fervor_of_the_Flagellant64.png -o Fervor_of_the_Flagellant64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/54/Turn_Demon64.png -o Turn_Demon64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/26/Momentum64.png -o Momentum64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c1/Werediggle_Curse.png -o Werediggle_Curse.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/1f/Piracy.png -o Piracy.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/28/Killer_Vegan.png -o Killer_Vegan.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/35/Emomancy.png -o Emomancy.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/76/Big_Game_Hunter.png -o Big_Game_Hunter.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e7/Demonologist.png -o Demonologist.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/41/Arch_Diggle_Screen_64.png -o Arch_Diggle_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/34/Far_Darrig_Screen_64.png -o Far_Darrig_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b9/Fell_Carrot_Screen_64.png -o Fell_Carrot_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/5c/Big_Blue_Screen_64.png -o Big_Blue_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c6/Lava_Eely_Screen_64.png -o Lava_Eely_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/7b/Magma_Carrot_Screen_64.png -o Magma_Carrot_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/ef/Icy_Dragon_Screen_64.png -o Icy_Dragon_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e7/Cold_Carrot_Screen_64.png -o Cold_Carrot_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/68/Magic_Dragon_Screen_64.png -o Magic_Dragon_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/95/Diggle_Commando_Screen_64.png -o Diggle_Commando_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/71/Kleptoblobby_Screen_64.png -o Kleptoblobby_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/fd/Thermoblobby_Screen_64.png -o Thermoblobby_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/58/Brax_run_d_0.png -o Brax_run_d_0.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/0d/Luck_Walk_Down_0.png -o Luck_Walk_Down_0.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/2b/Fatty_run_d_0.png -o Fatty_run_d_0.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/5e/Red_run_d_0.png -o Red_run_d_0.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/df/Squiddy_run_d_0.png -o Squiddy_run_d_0.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/39/Mush_run_d_0.png -o Mush_run_d_0.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6e/Sickly_Diggle_Screen_64.png -o Sickly_Diggle_Screen_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/63/Greeny_run_d_00.png -o Greeny_run_d_00.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/64/Eely_run_d_0.png -o Eely_run_d_0.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/85/Thrusty_run_d_0.png -o Thrusty_run_d_0.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/8f/Carrotty_idle_d_0.png -o Carrotty_idle_d_0.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/62/Molluscus.png -o Molluscus.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/84/Deth_idle_d_0.png -o Deth_idle_d_0.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/0b/Zomby_idle_d_0.png -o Zomby_idle_d_0.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/7d/Blobby_run_d_0.png -o Blobby_run_d_0.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/09/Puffball_64.png -o Puffball_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4f/Spell_black8_64.png -o Spell_black8_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/0a/Regal_Vim_64.png -o Regal_Vim_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/ff/Lobstery_Toughness.png -o Lobstery_Toughness.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b1/Fairy_Wodger_Fungal_Healing.png -o Fairy_Wodger_Fungal_Healing.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e2/Alcohol_poisoning64.png -o Alcohol_poisoning64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/7e/Unholy_warcry64.png -o Unholy_warcry64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/00/Skathas_roots64.png -o Skathas_roots64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/14/Magic_steel64.png -o Magic_steel64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/59/Fulminaric_bolt64.png -o Fulminaric_bolt64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/2c/Arctic_vortex64.png -o Arctic_vortex64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/ed/Dredmor_hard.png -o Dredmor_hard.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/08/Dredmor_medium.png -o Dredmor_medium.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/29/Dredmor_easy.png -o Dredmor_easy.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c7/Craftinglogo.png -o Craftinglogo.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/64/Tinkerer_Parts_%28Crafting%29.png -o Tinkerer_Parts_%28Crafting%29.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/da/Elven_Ingot_Grinder_%28Crafting%29.png -o Elven_Ingot_Grinder_%28Crafting%29.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/5c/Porta-Still_%28Crafting%29.png -o Porta-Still_%28Crafting%29.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e9/My_Little_Anvil_Junior_Smithing_Kit_%28Crafting%29.png -o My_Little_Anvil_Junior_Smithing_Kit_%28Crafting%29.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/d2/Modular_Alchemy_Kit_%28Crafting%29.png -o Modular_Alchemy_Kit_%28Crafting%29.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/0d/Disposable_Ingot_Press_%28Crafting%29.png -o Disposable_Ingot_Press_%28Crafting%29.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/be/Gameworldlogo.png -o Gameworldlogo.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/19/Skillslogo.png -o Skillslogo.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/40/Itemslogo.png -o Itemslogo.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/90/Enemieslogo.png -o Enemieslogo.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/eb/Attributeslogo.png -o Attributeslogo.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6d/Aboutlogo.png -o Aboutlogo.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/ee/Stat_int64.png -o Stat_int64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/fd/Voltaic_charge64.png -o Voltaic_charge64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/ec/Glacial_scythe64.png -o Glacial_scythe64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/31/Firehand64.png -o Firehand64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/85/Acid_burn64.png -o Acid_burn64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e3/Touch_of_Midas.png -o Touch_of_Midas.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/9e/Skill_necronomiconomics.png -o Skill_necronomiconomics.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/72/Skill_mathemagic.png -o Skill_mathemagic.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e6/Skill_vikingwizard.png -o Skill_vikingwizard.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/61/Magictraining2_64.png -o Magictraining2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/ad/Magictraining0_64.png -o Magictraining0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/98/Magictraining1_64.png -o Magictraining1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6b/Skill_magictraining.png -o Skill_magictraining.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/fb/Skill_astrologer.png -o Skill_astrologer.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/1f/Smithing3_64.png -o Smithing3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b0/Smithing2_64.png -o Smithing2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/1a/Smithing1_64.png -o Smithing1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/ef/Smithing0_64.png -o Smithing0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4f/Skill_smithing.png -o Skill_smithing.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/71/Skill_stealth3_64.png -o Skill_stealth3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/fb/Skill_burglary3_64.png -o Skill_burglary3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/a6/Skill_burglary1_64.png -o Skill_burglary1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e1/Skill_burglary2_64.png -o Skill_burglary2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/8a/Skill_burglary0_64.png -o Skill_burglary0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/28/Skill_stealth.png -o Skill_stealth.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c1/Crossbow1_64.png -o Crossbow1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/64/Crossbow0_64.png -o Crossbow0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/78/Skill_crossbow.png -o Skill_crossbow.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/aa/Shieldbearer4_64.png -o Shieldbearer4_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/26/Shieldbearer3_64.png -o Shieldbearer3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/f8/Shieldbearer2_64.png -o Shieldbearer2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/0b/Shieldbearer1_64.png -o Shieldbearer1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/39/Skill_shieldbearer.png -o Skill_shieldbearer.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/58/Dualwield3_64.png -o Dualwield3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/ca/Dualwield2_64.png -o Dualwield2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/68/Dualwield1_64.png -o Dualwield1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/bf/Skill_dualwield.png -o Skill_dualwield.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/d0/Macery3_64.png -o Macery3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b8/Mace_knowledge64.png -o Mace_knowledge64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/fe/Macery2_64.png -o Macery2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/dc/Macery1_64.png -o Macery1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c1/Macery0_64.png -o Macery0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4f/Skill_mace.png -o Skill_mace.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/52/Inventor64.png -o Inventor64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/15/Cog-jockey64.png -o Cog-jockey64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/a8/Mechanicker64.png -o Mechanicker64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6c/Trappist64.png -o Trappist64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/39/Skill_tinkerer.png -o Skill_tinkerer.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/ca/Thrown2_64.png -o Thrown2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/25/Thrown1_64.png -o Thrown1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/43/Skill_thrown.png -o Skill_thrown.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/9f/Staff-fighting3_64.png -o Staff-fighting3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/1a/Staff_secrets64.png -o Staff_secrets64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/3c/Staff-fighting2_64.png -o Staff-fighting2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e0/Staff-fighting1_64.png -o Staff-fighting1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6c/Staff-fighting0_64.png -o Staff-fighting0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c7/Skill_staff.png -o Skill_staff.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/03/Axemanship3_64.png -o Axemanship3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/13/Axe_mantra64.png -o Axe_mantra64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/23/Axemanship2_64.png -o Axemanship2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/32/Axemanship1_64.png -o Axemanship1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/52/Axemanship0_64.png -o Axemanship0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/33/Skill_axe.png -o Skill_axe.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/fe/Skill_archaeology1_64.png -o Skill_archaeology1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/2b/Skill_archaeology2_64.png -o Skill_archaeology2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/f7/Skill_archaeology0_64.png -o Skill_archaeology0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/d0/Skill_archaeology.png -o Skill_archaeology.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/43/Skill_assassination2_64.png -o Skill_assassination2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/70/Skill_assassination1_64.png -o Skill_assassination1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c3/Skill_assassination0_64.png -o Skill_assassination0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b9/Skill_assassination.png -o Skill_assassination.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/f6/Infernal_torus64.png -o Infernal_torus64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/40/Tactical_pyre64.png -o Tactical_pyre64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/06/Fireball64.png -o Fireball64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/72/Summon_wyrmling64.png -o Summon_wyrmling64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6e/Rune_of_exploding64.png -o Rune_of_exploding64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/7b/Dragons_breath64.png -o Dragons_breath64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/af/Skill_prometheanmagic.png -o Skill_prometheanmagic.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/76/Unconditional_love64.png -o Unconditional_love64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/62/Pyrokinesis64.png -o Pyrokinesis64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/20/Nerve_staple64.png -o Nerve_staple64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/a1/Crystal_healing64.png -o Crystal_healing64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b9/Psychokinetic_shove64.png -o Psychokinetic_shove64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/48/Sleep64.png -o Sleep64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/85/Skill_psionicist.png -o Skill_psionicist.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/5b/Skill_fleshshaper.png -o Skill_fleshshaper.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/42/Conjure_miasma64.png -o Conjure_miasma64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/ea/Zombyfycation64.png -o Zombyfycation64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/3b/Corpus_burst64.png -o Corpus_burst64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c8/Restoration64.png -o Restoration64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/fd/Fleshbore64.png -o Fleshbore64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/49/Meatshield64.png -o Meatshield64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/21/Skill_armour.png -o Skill_armour.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/fa/Stat_str64.png -o Stat_str64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/bd/Stat_con64.png -o Stat_con64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/11/Armourer1_64.png -o Armourer1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/df/Armourer0_64.png -o Armourer0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/ed/Swordplay3_64.png -o Swordplay3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/9c/Sword_lore64.png -o Sword_lore64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/98/Swordplay2_64.png -o Swordplay2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/12/Swordplay1_64.png -o Swordplay1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/8d/Swordplay0_64.png -o Swordplay0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/a2/Sidestepper64.png -o Sidestepper64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/8d/Leap64.png -o Leap64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/40/Skill_dodging.png -o Skill_dodging.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/f4/Skill_wandlore.png -o Skill_wandlore.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/3e/Wands2_64.png -o Wands2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/0d/Wands1_64.png -o Wands1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/f9/Wands0_64.png -o Wands0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/8f/Berserker1_64.png -o Berserker1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/5c/Skill_berserker.png -o Skill_berserker.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/a/a0/Berserker0_64.png -o Berserker0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c9/Perception3_64.png -o Perception3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/40/Perception2_64.png -o Perception2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/53/Perception1_64.png -o Perception1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/03/Skill_perception.png -o Skill_perception.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/d/d7/Skill_deadshot.png -o Skill_deadshot.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/2f/Deadshot1_64.png -o Deadshot1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c5/Deadshot0_64.png -o Deadshot0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c4/Vampirism2_64.png -o Vampirism2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/bf/Vampirism1_64.png -o Vampirism1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e6/Skill_vampirism.png -o Skill_vampirism.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/cd/Unarmed_art3_64.png -o Unarmed_art3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/4d/Skill_unarmed.png -o Skill_unarmed.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c7/Unarmed_art2_64.png -o Unarmed_art2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/95/Footwork64.png -o Footwork64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/e/e8/Unarmed_art1_64.png -o Unarmed_art1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/96/Unarmed_art0_64.png -o Unarmed_art0_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/7c/Skill_bloodmagic.png -o Skill_bloodmagic.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/48/Bloodmagic3_64.png -o Bloodmagic3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/bc/Bloodmagic2_64.png -o Bloodmagic2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/67/Bloodmagic1_64.png -o Bloodmagic1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/57/Montresors_wall64.png -o Montresors_wall64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/92/Animate_robot64.png -o Animate_robot64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/85/Thaumite_swarm64.png -o Thaumite_swarm64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/9e/Digging_ray64.png -o Digging_ray64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/5e/Mustache64.png -o Mustache64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/51/Blade_being64.png -o Blade_being64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/61/Skill_golemancer.png -o Skill_golemancer.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/06/Recursive_curse64.png -o Recursive_curse64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/05/Zephyric_transport64.png -o Zephyric_transport64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/0/0b/Zenziz64.png -o Zenziz64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/62/Curse_of_midas64.png -o Curse_of_midas64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/89/Tenebrous_rift64.png -o Tenebrous_rift64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/99/Eldritch_pillar64.png -o Eldritch_pillar64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/67/Fleeting_life64.png -o Fleeting_life64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/18/Mark_of_chthon64.png -o Mark_of_chthon64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c1/Nightmare_curse64.png -o Nightmare_curse64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/3/32/Divine_inscription64.png -o Divine_inscription64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/42/Stars_aligned64.png -o Stars_aligned64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/82/Celestial_aegis64.png -o Celestial_aegis64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/f2/Syzygy64.png -o Syzygy64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/f8/Blinding_goodness64.png -o Blinding_goodness64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/8/8c/Radiant_aura64.png -o Radiant_aura64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6f/Leylines2_64.png -o Leylines2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/53/Leylines1_64.png -o Leylines1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/63/Skill_leylines.png -o Skill_leylines.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b8/Skill_sword.png -o Skill_sword.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/9/9f/Weakness64.png -o Weakness64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/2/26/Blink64.png -o Blink64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/5/5b/Skill_mushroomlore.png -o Skill_mushroomlore.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/44/Skill_mushroom_lore2_64.png -o Skill_mushroom_lore2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/7/79/Skill_mushroom_lore1_64.png -o Skill_mushroom_lore1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/c/c7/Skill_alchemy.png -o Skill_alchemy.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/b/b9/Skill_alchemy2_64.png -o Skill_alchemy2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/1/1c/Skill_alchemy1_64.png -o Skill_alchemy1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/62/Alchemy3_64.png -o Alchemy3_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/f/ff/Alchemy2_64.png -o Alchemy2_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/6/6c/Alchemy1_64.png -o Alchemy1_64.webp
wget https://static.wikia.nocookie.net/dungeonsofdredmor/images/4/44/Alchemy0_64.png -o Alchemy0_64.webp
